defaults: &defaults
  working_directory: ~/GitHubUsers
  docker:
    - image: circleci/node:12

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
      - run:
          name: Setup Test Output Directory
          command: mkdir -p test-results/karma
      - run:
          name: Run tests
          command: npm test | npx tap-xunit > test-results/karma/results.xml
      - run:
          name: Run coverage report
          command: npm run coverage > coverage-report.lcov
      - store_artifacts:
          path: test-results/karma/results.xml
          destination: test-results/karma/
      - store_artifacts:
          path: coverage-report.lcov
          destination: reports
      - store_test_results:
          path: test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
