defaults: &defaults
  working_directory: ~/GitHubUsers
  docker:
    - image: circleci/node:12-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: githubusers-{{ .Branch }}-cache-{{ checksum "package.json"}}-{{ checksum ".circleci/config.yml"}}-{{ checksum "karma.conf.js"}}
          paths:
            - ./node_modules
  env:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Save env
          command: env > env.txt
      - store_artifacts:
          path: env.txt
          destination: reports
      - run:
          name: Save ssh
          command: ssh-keyscan github.com > ssh.txt
      - store_artifacts:
          path: ssh.txt
          destination: reports
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: githubusers-{{ .Branch }}-cache-{{ checksum "package.json"}}-{{ checksum ".circleci/config.yml"}}-{{ checksum "karma.conf.js"}}
      - run:
          name: Run eslint app
          command: npm run lint
      #- run:
      #    name: Run eslint tests
      #    command: npm run lint-test
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: githubusers-{{ .Branch }}-cache-{{ checksum "package.json"}}-{{ checksum ".circleci/config.yml"}}-{{ checksum "karma.conf.js"}}
      - run:
          name: Run tests + coverage
          command:  npm run test-ci --no-watch --no-progress --browsers=ChromeHeadless
      - store_artifacts:
          path: reports/junit/
          destination: reports/junit/
      - store_artifacts:
          path: reports/detailed/
          destination: reports/detailed/
      - store_artifacts:
          path: coverage-report.lcov
          destination: reports
      - store_test_results:
          path: test-results
      - store_test_results:
          path: reports/detailed
      - store_artifacts:
          path: coverage/html
          destination: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - env
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - build-dist:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
