defaults: &defaults
  working_directory: ~/GitHubUsers
  docker:
    - image: circleci/node:12-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: githubusers-{{ .Branch }}-cache-{{ checksum "package.json"}}-{{ checksum ".circleci/config.yml"}}-{{ checksum "karma.conf.js"}}
          paths:
            - ./node_modules
  env:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Save env
          command: env > env.txt
      - store_artifacts:
          path: env.txt
          destination: reports
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: githubusers-{{ .Branch }}-cache-{{ checksum "package.json"}}-{{ checksum ".circleci/config.yml"}}-{{ checksum "karma.conf.js"}}
      - run:
          name: Run lint
          command: npm run eslint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: githubusers-{{ .Branch }}-cache-{{ checksum "package.json"}}-{{ checksum ".circleci/config.yml"}}-{{ checksum "karma.conf.js"}}
      - run:
          name: Run lint
          command: npm run eslint
      - run:
          name: Run tests + coverage
          command:  npm run test-ci --no-watch --no-progress --browsers=ChromeHeadless
      - store_artifacts:
          path: reports/junit/
          destination: reports/junit/
      - store_artifacts:
          path: reports/detailed/
          destination: reports/detailed/
      - store_artifacts:
          path: coverage-report.lcov
          destination: reports
      - store_test_results:
          path: reports/junit
  build-dist:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: githubusers-{{ .Branch }}-cache-{{ checksum "package.json"}}-{{ checksum ".circleci/config.yml"}}-{{ checksum "karma.conf.js"}}
      - run:
          name: Build prod
          command:  npm run build
      - store_artifacts:
          path: dist
          destination: dist
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy-dist:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "58:16:f3:26:28:34:a1:6e:b8:34:59:7e:c4:b3:79:7d"
      - attach_workspace:
          at: ./
      - run:
          - name: Add github to known hosts
          - command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Install deps
          command: |
            sudo npm i -g --silent gh-pages@2.0.1
            git config user.email "ci-build@intrafoundation.com"
            git config user.name "ci-build"
      - run:
          name: Deploy dist to gh-pages branch
          command: sudo gh-pages --dist dist
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - env
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - build-dist:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy-dist:
          requires:
            - build
            - test
            - build-dist
          filters:
            branches:
              only: master
